### ISSUE TITLE
Can we make search on more than one bookshelf in a single run?

### ISSUE THREAD

**Issue by hwasiti** [andre-st/goodreads#10]
The current update of `likeminded.pl` is just amazing. I have re-run the search and getting with some books ~4000-5000 members. Your code is getting close to the ideal search that GR would have done if they would apply this feature using their database.

Also I feel the current update, solved an issue where every few hours the code was stopped saying there was no response from Goodreads or something like that. Now the current run for the last 24 hours never stopped. Maybe this is related to my pc or internet problem.

The current run will take ~7 days and not finished yet ( ALL books search for ~350 books), so I could not experiment  whether there is an option to let the --shelf parameter include more than one shelf. Is that possible?

It seems another several search run with certain shelves combined is interesting too. With all books and a lot of them are very popular, the results are generic as you said. 

In case you don't like the idea, the workaround is easy. I will create meta-shelves for major topics, and include the books of the other shelves related into those major topic shelves. But when I want to add a new book then I have to add the book manually into the meta-shelf beside adding it to its correct shelf. I wished if there was a way GR can add automatically all the assigned children shelves into a meta-shelf. If your code works with more than one shelf, then this meta-shelf is not necessary.

**Comment by andre-st** [comment]
Hello Haider, thanks again for your feedback and ideas

multiple shelves are not possible at the moment but it shouldn't be too hard to implement this.
Maybe: `--shelf=name1,name2,name3` or `--shelf=name1 --shelf=name2` ... or both styles.

At the moment, I'm using one special shelf for this and other programs (recentrated.pl). 
It contains a "best of" selecton with ~100 books, which are already somehow representative of its readers, e.g., technical non-fiction.

The last update also included automatic retries on some errors, so users can run the program unattended. I also made changes on connection reuse (reduces number of slow SSL handshakes).

**Comment by hwasiti** [comment]
> At the moment, I'm using one special shelf for this and other programs (recentrated.pl).
It contains a "best of" selecton with ~100 books, which are already somehow representative of its readers, e.g., technical non-fiction.

That's a good idea!

> The last update also included automatic retries on some errors, so users can run the program unattended. I also made changes on connection reuse (reduces number of slow SSL handshakes).

hmm.. That's why I  am feeling the improvement. Now it has been almost 2 days running without a single issue in the connection. When I ran the old version (the book title search version: a day before your commit for the author search version), I had even had to reboot the Windows once to solve the a network problem that made the code not able to proceed to continue downloading. Now this version is much better in every way.

**Comment by andre-st** [comment]
The --shelf parameter will be in the next update, but I'm little busy with other things, at the moment.

**Comment by andre-st** [comment]
You can use  ./likeminded.pl --shelf=music --shelf=science ... now
