### ISSUE TITLE
a list of ALL dependencies is needed.

### ISSUE THREAD

**Issue by WaterSibilantFalling** [andre-st/goodreads#15]
Ok, I used to be a Perl programmer, so I can slowly look at every script, one by one, and install each missing library. However, some people have never been Perl programmers.

A list of all dependencies is needed, and either an apt(itude) or cpan/cpanm or some such command line to install them all that a user can copy an paste into their terminal. 

After running that command, each of these excellent - they are excellent - scripts should then run without complaint. 

e.g. I tried cpanm, then aptitude, and finally google to find the Goodscrapes library. Ah, it's in the /lib/ subdir. Good, but a pointer would have been helpful.

**Comment by WaterSibilantFalling** [comment]
```
...../goodreads$ grep -h "^use " *.pl */*.pm | sort -u

use 5.18.0;
use Cache::Cache qw( $EXPIRES_NEVER $EXPIRES_NOW );
use Cache::FileCache;
use Carp qw( croak );
use FindBin;
use Getopt::Long;
use Goodscrapes;
use HTML::Entities;
use IO::File;
use List::MoreUtils qw( uniq );
use Log::Any '$_log', default_adapter => [ 'File' => '/var/log/good.log' ];
use POSIX       qw( strftime );
use POSIX       qw( strftime floor );
use Pod::Usage;
use Text::CSV qw( csv );
use Time::HiRes qw( time tv_interval );
use Time::Piece;
use URI::Escape;
use WWW::Curl::Easy;
use base 'Exporter';
use cookie-file F<./.cookie> (only required for private accounts).
use cookie-file F<./.cookie> (only required for private accounts).
use lib "$FindBin::Bin/lib/";
use strict;
use utf8;
use warnings qw(all);
use warnings;

```


which, with a clean out, means: 

```

cpanm -i Cache::Cache Cache::FileCache Carp FindBin \
      Getopt::Long HTML::Entities IO::File List::MoreUtils \
       Log::Any Pod::Usage Text::CSV Time::HiRes \
        Time::Piece URI::Escape WWW::Curl::Easy

```

**Comment by andre-st** [comment]
Thanks for your feedback.

These dependencies are listed in the [Makefile](https://github.com/andre-st/goodreads/blob/master/Makefile) and and should install via `$ sudo make` (can be improved, though).

Every script has a description file ($scriptname.md) which includes an install/usage section including `make`, e.g.,  https://github.com/andre-st/goodreads/blob/master/savreviews.md
Some description files also have detailed notes about the limitations etc., reading them is recommended.

Every heading here https://github.com/andre-st/goodreads/blob/master/README.md links to such a description file. 

I'll think about how to make `make` more obvious, thanks!

**Comment by andre-st** [comment]
For now, I added a section "installation" to the main README.md (I think this was the problem) and a comment to the install sections on every single script-description page, too.
Perhaps I will also add an INSTALL.txt file.

**Comment by WaterSibilantFalling** [comment]
Sorry, my bad. I didn't see - well, at least I didn't run - the Makefile.  Makes sense.

**Comment by andre-st** [comment]
Nevertheless, you had a point. When this happens, it's a usability or documentation problem. In the past, I added script for script and linked them individually in the GR forums, and somewhat forgot about the Toolbox as a whole. Installing deps (etc) via the Makefile was not obvious and `make` was just mentioned somewhere on the script-pages. If someone just skims over the documentation or directory listing, which I often do too, he will find it more easily, now.
