### ISSUE TITLE
[Feature request] More filters for friendrated

### ISSUE THREAD

**Issue by Tikotik** [andre-st/goodreads#16]
It would be nice to filter books output with flags of publishing year and no. of reads:
like 'books with less than 1000 ratings(/read) and (First)published between 1950 to 1980 and rated 4 or 5 stars by my friends'.

**Comment by andre-st** [comment]
Yes, this is useful.
There are new optional parameters now. According to your example:

`./friendrated.pl --maxratings=1000 --minyear=1950 --maxyear=1980 --rated=4 ...`

I also added two columns "Num GR Ratings" and "Year Published" to the final HTML file.
