### ISSUE TITLE
make has failed for libcurl

### ISSUE THREAD

**Issue by hwasiti** [andre-st/goodreads#2]
Hi 

Tried it on Ubuntu 14 and got this error:

```
perl -MCPAN -e 'install Cache::FileCache, WWW::Curl::Easy, Text::CSV, Log::Any, XML::Writer' || (echo "Please send your error messages to datakadabra@gmail.com" && false)
Reading '/home/haider/.cpan/Metadata'
  Database was generated on Fri, 22 Jun 2018 05:54:29 GMT
Cache::FileCache is up to date (undef).
Running install for module 'WWW::Curl::Easy'
Running make for S/SZ/SZBALINT/WWW-Curl-4.17.tar.gz
Checksum for /home/haider/.cpan/sources/authors/id/S/SZ/SZBALINT/WWW-Curl-4.17.tar.gz ok

  CPAN.pm: Building S/SZ/SZBALINT/WWW-Curl-4.17.tar.gz

Locating required external dependency bin:curl-config... missing.
Unresolvable missing external dependency.
Please install 'curl-config' seperately and try again.
NA: Unable to build distribution on this platform.
No 'Makefile' created'YAML' not installed, will not store persistent state
  SZBALINT/WWW-Curl-4.17.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- NOT OK
Running make test
  Make had some problems, won't test
Running make install
  Make had some problems, won't install
Text::CSV is up to date (1.95).
Log::Any is up to date (1.705).
XML::Writer is up to date (0.625).
Could not read metadata file. Falling back to other methods to determine prerequisites
chmod +x *.pl
```

**Comment by andre-st** [comment]
Seems you need to install curl(-config) by hand:

> Please install 'curl-config' seperately and try again.

$ apt-get install libwww-curl-perl curl-config

Does this work for you? (Don't have a Ubuntu/Debian here atm)

**Comment by hwasiti** [comment]
I got this:
`E: Unable to locate package curl-config`
I will try to search for a solution in SO

**Comment by hwasiti** [comment]
Now it works. Thanks!
I tried a lot of ways, but now it works. Unfortunately I am not quite remember which one eventually worked. But seems the last tab that I closed searching for a solution was this:
https://www.linuxquestions.org/questions/linux-newbie-8/cannot-find-curl-config-in-ubuntu-13-04-a-4175480992/
It was either:
`sudo apt-get update && sudo apt-get install libcurl4-gnutls-dev`

or

`apt-get install libwww-curl-perl curl-config`


Now downloading the reviews for my 386 books! Yay!!

Great work bro!!

It is a shame that Goodreads seems not interested to include this feature on its platform. That wouldn't be too difficult for them, but maybe resource intensive. However, it is bought by Amazon now, and resource allocation for this should not be a problem. 

Heck, Amazon Kindle even had this feature on its Kindle website which has been discontinued in favor of merging it with Goodreads.

**Comment by andre-st** [comment]
Thank you, Haider.
I overhauled **likeminded.pl**: 
- it compares authors, not books, now - I found the books-version too narrow; the current results are better (more matches with my hand-curated followees list), it takes longer but will reuse already downloaded reviews
- It  creates a HTML file with a table: see [likeminded.md](https://github.com/andre-st/goodreads/blob/master/likeminded.md)
- I extended lib/Goodscrapes.pm in order to load all books of an author and removed some quirks (replaces HTML entities in titles/names)

You need to `make likeminded` again or, if simpler, just run as root: 
`perl -MCPAN -e 'install HTML::Entities'`

I agree, Goodreads uses Amazon technology ([here](https://www.glasswaves.co/selected_projects.txt) or [here](https://www.goodreads.com/jobs?id=597248#openPositions)), and should have contact to Amazon engineers/consultants etc. But it's hard to judge from the outside.

**Comment by hwasiti** [comment]
The new version sounds great!
I will try it after tinkering with the results of the older version for my books. 

Thanks André for sharing your work with the open source community.

**Comment by hwasiti** [comment]
The Social Reading Team's job offer at Goodreads that you mentioned is encouraging, but unfortunately, Shaun who seems an engineer at Goodreads mentioned two times that they are not working on this feature (which I am pretty sure you are aware of):
https://www.goodreads.com/topic/show/298531-is-there-an-option-to-do-a-general-search-for-people-with-similar-readin?comment=181375952&page=5#comment_181375952

Shaun wrote in 2017 : _"Hi all, thanks for letting us know you're still interested in seeing the addition of this feature. Even though this not in our current road map, our developers are aware of the request"_

message 213: by Shaun, Goodreads Expert Feb 16, 2018 06:10AM
_We appreciate everyone's comments here! Even though we're not looking to work on a feature like this at the moment, it's great to see the amount of people interested in it (an easier way to search for people with same/similar reading tastes)._ 

As you said, it is difficult to judge from outside. Sometimes because developing a feature takes so long time, they are not giving any promise.

**Comment by andre-st** [comment]
I close this make-issue due to new Docker support.
The [Dockerfile](https://github.com/andre-st/goodreads-toolbox/blob/master/Dockerfile) lists everything that is needed for a working installation on an Ubuntu system.
