### ISSUE TITLE
Undefined subroutine &WWW::Curl::Easy::CURLOPT_TCP_KEEPALIVE

### ISSUE THREAD

**Issue by Symcrapico** [andre-st/goodreads#20]
Hi, I'm trying to make the search.pl script work but I get the following:

> me@www ~/tmp/goodreads $ ./search.pl --order=stars,num_ratings --ratings=10000 linux
> Reporting Bugs:
>     Report bugs to <datakadabra@gmail.com> or use Github's issue tracker
>     <https://github.com/andre-st/goodreads/issues>
> 
> Searching books:
> 
>  about..... linux
>  rated by.. 10000 members or more
>  order by.. stars, num_ratings, year
>  progress.. Undefined subroutine &WWW::Curl::Easy::CURLOPT_TCP_KEEPALIVE called at /home/akenny/tmp/goodreads/lib/Goodscrapes.pm line 2094.

Any idea?

**Comment by andre-st** [comment]
Thanks for reporting this. Seems like your Curl version doesn't define the constant `CURLOPT_TCP_KEEPALIVE`. 

If you like to make it work now (until I provide a solution), just edit lib/Goodreads.pm and put a # at line 2094 which comments out the use of this constant. If there are other undefined constants, comment them out too.

**Comment by andre-st** [comment]
Thanks for reporting this. Seems like your Curl version doesn't define the constant `CURLOPT_TCP_KEEPALIVE`.

I committed an update. 
just run `git pull` in your `/home/akenny/tmp/goodreads` directory.

Does it work for you?

PS: `--ratings=10000` is too high; there are no Linux books with that many ratings on Goodreads, IIRC; I would start with the defaults and fine-tune later; the result is sorted anyway
`./search.pl linux`

**Comment by Symcrapico** [comment]
Yes, it did fix the problem. 

As for the search query, it was just an example!

Thanks!

PS: Is there a way to do a search to get the best rated books of a genre (eg. SciFi) with say 10000 ratings? That would be awesome!!

**Comment by andre-st** [comment]
Re: searching by genre

The current search.pl program does not implement this, but the Goodreads community shelves are already listing very popular books. The SciFi shelf, for instance, contains 1250 books with often more than 100'000 ratings: https://www.goodreads.com/shelf/show/science-fiction

Sometimes, Goodreads writes blog-posts about popular books of a genre: https://www.goodreads.com/blog/show/987-top-50-science-fiction-books-on-goodreads

If you find more bugs or have other suggestions for improvement, feel free to open a new issue. This makes it easier to manage different requests separately.
