### ISSUE TITLE
Won't read shelves with dashes

### ISSUE THREAD

**Issue by dogbertgh** [andre-st/goodreads#22]
I can't get the script to accept shelves with dashes in the name.  For example, ./likeminded.pl --shelf=read-hugo ######### returns "Loading authors from "read-hugo"...[FATAL] No books found."  The script works as expected f I rename the shelf to get rid of the dash(es).

**Comment by andre-st** [comment]
I tried to reproduce this by creating a shelf "read-hugo" (normal and 'exclusive' ), but the script didn't report any error to me. Too, my "watch-ratings" shelf is checked every day (`recentrated.pl`) and I often used "watch-ratings" to test `likeminded.pl`.

So I doubt it's just the dashes, there must be something else. 

Can you send me your Goodreads user ID via e-mail? My mail address is datakadabra@gmail.com

Thank you for reporting this.

**Comment by andre-st** [comment]
~~Does `./likeminded.pl --shelf=read-hugo 18418712` work for you (using my account ID)? 
Should print: "Loading authors from "read-hugo"...    5 authors"~~

Update: I removed the "read-hugo" shelf again as there was no response from the issue opener in 5 weeks. I'll close this issue as it was not reproducible.
