### ISSUE TITLE
Create dockerfile

### ISSUE THREAD

**Issue by blyszcz** [andre-st/goodreads#30]
Could you provide a working dockerfile / docker-compose?

**Comment by andre-st** [comment]
I've added a Dockerfile to the sources. For convenience, there are Docker make-targets, now:

~~obsolete code~~

~~This will build the Docker image, and create a directory called "my-results" in your current user's home directory and bindmounts it to a data-directory in the container. 
Change as you like.~~ 

Many programs in the toolbox write HTML files to the "list-out" directory. Your web-browser must somehow access these HTML files in the container. You could copy them to the host via `docker cp` or, in my opinion, more conveniently access them through the "~ / my-results" directory. Another option would be a lightweight httpd.

I'm not sure if that fits in with the way you use Docker. If you have better ideas, I would like to read them.

**Comment by andre-st** [comment]
I replaced the bindmount version with a lightweight web-server, now. I think, this is less rude than creating directories in the home-directory and access to the html reports is convenient, too:
```console
$ make docker-image
$ make docker-run DOCKER_HTPORT=8080
% ./any-script.pl --help
```
