### ISSUE TITLE
GR login via library currently broken

### ISSUE THREAD

**Issue by andre-st** [andre-st/goodreads#38]
Goodreads seems to have changed their login process (probably different URLs, OpenID, etc. at first glance). If I find time, I'll take care of it. Unfortunately, I won't be able to do that in the short term. As a result, some programs are currently not working. When using only the library, many operations also work without a login, only then more slowly.

**Comment by WaterSibilantFalling** [comment]
In my case, I had to set a new password.
But the appearance of the page also, at the same time, Changed
|
