### ISSUE TITLE
If someone can fix the login bug, post it here

### ISSUE THREAD

**Issue by Taylor-eOS** [andre-st/goodreads#39]
The issues page is open again. If someone has the understanding to fix the login bug, please post it here, so we can copy in the changes. The original developer seems to no longer be active. The problem is in lib/Goodscrapes.pm, involving line 258. It somehow needs to be adapted to the new Goodreads design.
I'm looking forward to this working again.

**Comment by andre-st** [comment]
Changing the URL was part of the correction, but a few more things were needed to make the login work again in the latest version. Details of the change can be found at: https://github.com/andre-st/goodreads-toolbox/commit/32e9d2da35f463ee32bf73640f759d1e5a5e2bbc

**Comment by Taylor-eOS** [comment]
Thanks, I already installed it, but unfortunately on my system (Linux Mint) I have to manually install a bunch of python packages to make it work, which took like half a day last time. That kept me from using it.

**Comment by andre-st** [comment]
Alternatively, you might want to try Docker (probably apt install docker + ... + Docker guide in my README.md). Docker will download a small Linux container (~100MB) with all dependencies, saving time and headaches. Then you work in the container and delete it when you're done.
